### PR TITLE
Timeout error

### LINKED ISSUE #115: "Timeout exceeded while waiting for an event" error is thrown in the non-interactive mode.
"waitForNetworkIdle" method fails in non-interactive mode.

### PR DESCRIPTION
**Pull request by ilayda21**
## Done
- Replaced waitForNetworkIdle with waitForTimeout
- Updated the version

## QA
- Checkout the feature branch.
- Run `yarn` command to install dependencies.
- Run `yarn dev add-posts <post-id> -r emea`
- Verify job posts are created.

Fixes #115

### CODE REVIEW

File: src/automations/Job.ts [hunk 1]
```diff
@@ -254,9 +254,10 @@ export default class Job {
     private async loadAllJobs() {
         await this.page.waitForSelector(".job");
         let morePageButton = await this.page.$("#show_more_jobs");
+
         while (morePageButton) {
             morePageButton.click();
-            await this.page.waitForNetworkIdle();
+            await this.page.waitForTimeout(3000);
```
Comment (tbille) [inline src/automations/Job.ts:260]: is there a scenario where you can have 10 pages?

Comment (ilayda21) [reply src/automations/Job.ts:260]: I dont know

Comment (tbille) [reply src/automations/Job.ts:260]: how many pages do you see as an admin?

Comment (ilayda21) [reply src/automations/Job.ts:260]: 6 pages

Comment (goulinkh) [reply src/automations/Job.ts:260]: `waitForTimeout` it a very risky approach were if someones internet or PC is slow the result may differ, there are multiple ways to wait in puppeteer, if `waitForNetworkIdle` isn't working try providing an argument, see [this comment](https://github.com/puppeteer/puppeteer/issues/1552#issuecomment-350954419) for more info about the options.
Otherwise you can use [`waitForSelector`](https://puppeteer.github.io/puppeteer/docs/puppeteer.page.waitforselector/) if you are waiting for a given UI element.
There different `waitFor` methods that puppeteer provides, the last one that you will need is the hard written delay one!

Comment (ilayda21) [reply src/automations/Job.ts:260]: there is no element to check i will check the job count

File: src/automations/Job.ts [hunk 2]
```diff
@@ -251,12 +251,28 @@ export default class Job {
...
             morePageButton.click();
-            await this.page.waitForNetworkIdle();
+            await this.page.waitForFunction(
+                (args: string[]) => {
+                    const innerText =
+                        document.getElementById("jobs_pagination")?.innerText;
+                    return args[0] !== innerText;
+                },
+                {},
+                [pageText]
```
Comment (goulinkh) [inline src/automations/Job.ts:274]: Very cool! one small note, you can name the argument:
```ts
await this.page.waitForFunction({pageText} => {
   const innerText = document.getElementById("jobs_pagination")?.innerText;
   return pageText !== innerText;
}, {}, {pageText});
```

File: src/automations/Job.ts [hunk 3]
```diff
@@ -251,12 +251,29 @@ export default class Job {
...
         await this.page.waitForSelector(".job");
         let morePageButton = await this.page.$("#show_more_jobs");
+        let pageText;
         while (morePageButton) {
+            pageText = await this.getPaginationElementText();
             morePageButton.click();
-            await this.page.waitForNetworkIdle();
+            await this.page.waitForFunction(
+                (pageText: string) => {
+                    console.log(pageText)
```
Comment (tbille) [inline src/automations/Job.ts:269]: Hello console.log
